name=OLEDHelper
version=1.0.0
author=L8onESP32
maintainer=L8onESP32
sentence=A helper library for SSD1306 OLED display
paragraph=Provides easy methods to display potentiometer values and text.
category=Display
url=https://github.com/L8onESP32/Wokwi-ESP32-Simulations
architectures=esp32
